name = "pomo-tm"
main = ".open-next/worker.js"
compatibility_date = "2026-09-21"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[services]]
binding = "WORKER_SELF_REFERENCE"
service = "pomo-tm"

[[d1_databases]]
binding = "pomo_db"
database_name = "pomo-db"
database_id = "6a87c217-8355-48d8-972e-32410952df34"
